name: physio_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.5.0
  provider: ^4.0.3
  intl: ^0.16.1
  intl_phone_number_input: ^0.3.0
  dropdown_formfield: ^0.1.1
  http: ^0.12.0+4
  shared_preferences: ^0.5.3+1
  agora_rtc_engine: ^1.0.5
  permission_handler: ^3.0.0
  file_picker: ^1.5.0+2
  chewie: ^0.9.10
  video_player: ^0.10.8+1
  firebase_messaging: ^6.0.13
  edge_alert: ^0.0.1
  vibration: ^1.2.4
  flutter_ringtone_player: ^2.0.0
  wakelock: ^0.1.4+1
  firebase_analytics: ^5.0.11

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
